Repository MicrosoftStudentChapter/MAKEATHON, pull requests merged in 2021-01, with the labels that each got.

#17 Setup URL config
  Makeathon3077/settings.py
  Makeathon3077/urls.py
  webpages/templates/webpages/index.html
  webpages/urls.py
  webpages/views.py
Labels: Backend

#18 Modularized settings
  Makeathon3077/settings/__init__.py
  Makeathon3077/settings/base.py
  Makeathon3077/settings/dev.py
  Makeathon3077/settings/prod.py
  Makeathon3077/wsgi.py
  Pipfile
  Pipfile.lock
  manage.py
Labels: Backend

#22 Tests for index url and index view done
  .vscode/settings.json
  tests/__init__.py
  tests/test_urls.py
  tests/test_views.py
Labels: Backend

#31 .travis.yml file added
  .travis.yml
Labels: DevOps

#26 Speakers and Judges
  templates/Speakers_and_Judges/index.html
  templates/Speakers_and_Judges/static/css/style.css
  templates/Speakers_and_Judges/static/images/arrow-left.png
  templates/Speakers_and_Judges/static/images/arrow-right.png
  templates/Speakers_and_Judges/static/images/git.png
  templates/Speakers_and_Judges/static/images/image12.png
  templates/Speakers_and_Judges/static/images/img1.png
  templates/Speakers_and_Judges/static/images/img2.png
  templates/Speakers_and_Judges/static/images/img3.png
  templates/Speakers_and_Judges/static/images/insta.png
  templates/Speakers_and_Judges/static/images/link.png
  templates/Speakers_and_Judges/static/images/pichai.png
  templates/Speakers_and_Judges/static/js/index.js
Labels: Frontend

#28 Change Alignment of About-Makeathon Page
  templates/About/index.html
  templates/About/static/css/style.css
  templates/About/static/images/background-image.png
  templates/About/static/images/registration-icon.svg
  templates/About/static/images/registrations-icon.png
  templates/About/static/images/terminal-icon.svg
  templates/About_MLSC/.vscode/settings.json
  templates/About_MLSC/index.html
  templates/About_MLSC/static/css/style.css
  templates/About_MLSC/static/images/background-image.png
  templates/About_MLSC/static/images/registration-icon.svg
  templates/About_MLSC/static/images/registrations-icon.png
  templates/About_MLSC/static/images/terminal-icon.svg
Labels: Frontend, bug

#23 Faq
  templates/FAQ/.vscode/launch.json
  templates/FAQ/index.html
  templates/FAQ/static/css/style.css
  templates/FAQ/static/images/bg.png
  templates/FAQ/static/js/index.js
Labels: Frontend

#38 Modified contributing.md with developer instructions and added .env.e…
  .env.example
  CONTRIBUTING.md
Labels: documentation

#41 Linting test setup
  .pre-commit-config.yaml
  .travis.yml
  CONTRIBUTING.md
  Makeathon3077/asgi.py
  Makeathon3077/settings/base.py
  Makeathon3077/settings/dev.py
  Makeathon3077/settings/prod.py
  Makeathon3077/urls.py
  Makeathon3077/wsgi.py
  Pipfile
  Pipfile.lock
  README.md
  manage.py
  templates/About/index.html
  templates/About/static/css/style.css
  templates/About_MLSC/.vscode/settings.json
  templates/About_MLSC/index.html
  templates/About_MLSC/static/css/style.css
  templates/FAQ/.vscode/launch.json
  templates/FAQ/index.html
  templates/FAQ/static/css/style.css
  templates/FAQ/static/js/index.js
  templates/Home/index.html
  templates/Home/static/css/style.css
  templates/Home/static/js/index.js
  templates/Prizes/index.html
  templates/Prizes/static/css/style.css
  templates/Speakers_and_Judges/index.html
  templates/Speakers_and_Judges/static/css/style.css
  templates/Speakers_and_Judges/static/js/index.js
  templates/Sponsors/index.html
  templates/Sponsors/static/css/style.css
  templates/Timeline/index.html
  templates/Timeline/static/css/style.css
  templates/Tracks/index.html
  templates/Tracks/static/css/style.css
  tests/test_views.py
  webpages/admin.py
  webpages/apps.py
  webpages/models.py
  webpages/templates/webpages/index.html
  webpages/tests.py
  webpages/urls.py
  webpages/views.py
Labels: DevOps, Tests

#39 Fix homepage bugs
  templates/Home/static/css/style.css
Labels: Frontend, bug

#42 Issue update faq
  templates/FAQ/static/css/style.css
  templates/Home/static/css/style.css
Labels: Frontend, bug

#49 Setup for deployment
  Makeathon3077/settings/base.py
  Makeathon3077/settings/prod.py
  Pipfile
  Pipfile.lock
  Procfile
  requirements.txt
  runtime.txt
Labels: Backend, DevOps

#48 Tracks
  templates/Tracks/index.html
  templates/Tracks/static/css/style.css
  templates/Tracks/static/images/tracksbg.jpg
  templates/Tracks/static/js/index.js
Labels: Frontend, bug

#45 Fixed positioning of time-left image
  templates/Home/index.html
  templates/Home/static/css/style.css
  templates/Home/static/images/title-1.png
  templates/Home/static/images/tleft-1.png
  templates/Home/static/images/tleft-2.png
  templates/Home/static/js/index.js
Labels: Frontend, bug, enhancement

#62 animations added
  templates/Home/index.html
  templates/Home/static/css/style.css
  templates/Home/static/js/index.js
  templates/Sponsors/index.html
  templates/Sponsors/static/css/style.css
  templates/Sponsors/static/js/index.js
  templates/Tracks/index.html
  webpages/static/webpages/About/static/css/style.css
  webpages/static/webpages/About_MLSC/static/css/style.css
  webpages/static/webpages/FAQ/static/css/style.css
  webpages/static/webpages/Tracks/static/css/style.css
  webpages/static/webpages/Tracks/static/images/tracksbg.jpg
  webpages/static/webpages/Tracks/static/images/user-people-network-circuit-board-link-connection-technology.jpg
  webpages/static/webpages/Tracks/static/js/index.js
  webpages/templates/webpages/About/index.html
  webpages/templates/webpages/About_MLSC/index.html
  webpages/templates/webpages/Tracks/index.html
Labels: Backend, enhancement
